ignore:
  # rollup
  - vulnerability: GHSA-mw96-cpmx-2vgc
  # node-forge
  - vulnerability: GHSA-5m6q-g25r-mvwx
  - vulnerability: GHSA-q67f-28xg-22rw
  - vulnerability: GHSA-ppp5-5v6c-4jwp
  - vulnerability: GHSA-2328-f5f3-gj25
  # path-to-regexp
  - vulnerability: GHSA-j3q9-mxjg-w52f
  # lodash
  - vulnerability: GHSA-r5fr-rjxr-66jc
  # vite - only affects dev server - needs vitest and @vitejs/plugin-react-swc to be updated
  - vulnerability: GHSA-p9ff-h696-f583
  # vite - only affects server.fs.deny which we don't use
  - vulnerability: GHSA-v2wj-q39q-566r
