sonar.organization=nhsdigital
sonar.projectKey=NHSDigital_eps-prescription-tracker-ui
sonar.host.url=https://sonarcloud.io

# Global exclusions
sonar.coverage.exclusions=\
    **/*.test.*, \
    **/mock*, \
    **/__mocks__*, \
    **/jest.*.ts, \
    scripts/*, \
    packages/cdk/**, \
    packages/cpt-ui/vite*.config.ts, \
    packages/common/commonTypes/**, \
    **/vitest.config.ts

sonar.cpd.exclusions=\
    packages/cloudfrontFunctions/tests/**, \
    packages/cdk/nagSuppressions.ts, \
    **/mock*, \
    **/__mocks__*, \
    **/*.test.ts*, \
    **/vitest.config.ts

# Define the modules
sonar.modules=\
    cpt-ui, \
    cloudfrontFunctions, \
    cognito, \
    CIS2SignOutLambda, \
    prescriptionListLambda, \
    prescriptionDetailsLambda, \
    patientSearchLambda, \
    trackerUserInfoLambda, \
    sessionManagementLambda, \
    selectedRoleLambda, \
    common-middyErrorHandler, \
    common-pdsClient, \
    common-authFunctions, \
    common-doHSClient, \
    common-dynamoFunctions

# Modules
cpt-ui.sonar.projectBaseDir=packages/cpt-ui
cpt-ui.sonar.sources=.
cpt-ui.sonar.javascript.lcov.reportPaths=coverage/lcov.info


cloudfrontFunctions.sonar.projectBaseDir=packages/cloudfrontFunctions
cloudfrontFunctions.sonar.sources=.
cloudfrontFunctions.sonar.javascript.lcov.reportPaths=coverage/lcov.info


cognito.sonar.projectBaseDir=packages/cognito
cognito.sonar.sources=.
cognito.sonar.javascript.lcov.reportPaths=coverage/lcov.info


CIS2SignOutLambda.sonar.projectBaseDir=packages/CIS2SignOutLambda
CIS2SignOutLambda.sonar.sources=.
CIS2SignOutLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info


prescriptionListLambda.sonar.projectBaseDir=packages/prescriptionListLambda
prescriptionListLambda.sonar.sources=.
prescriptionListLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info

patientSearchLambda.sonar.projectBaseDir=packages/patientSearchLambda
patientSearchLambda.sonar.sources=.
patientSearchLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info

prescriptionDetailsLambda.sonar.projectBaseDir=packages/prescriptionDetailsLambda
prescriptionDetailsLambda.sonar.sources=.
prescriptionDetailsLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info


trackerUserInfoLambda.sonar.projectBaseDir=packages/trackerUserInfoLambda
trackerUserInfoLambda.sonar.sources=.
trackerUserInfoLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info


sessionManagementLambda.sonar.projectBaseDir=packages/sessionManagementLambda
sessionManagementLambda.sonar.sources=.
sessionManagementLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info


selectedRoleLambda.sonar.projectBaseDir=packages/selectedRoleLambda
selectedRoleLambda.sonar.sources=.
selectedRoleLambda.sonar.javascript.lcov.reportPaths=coverage/lcov.info


common-middyErrorHandler.sonar.projectBaseDir=packages/common/middyErrorHandler
common-middyErrorHandler.sonar.sources=.
common-middyErrorHandler.sonar.javascript.lcov.reportPaths=coverage/lcov.info

common-pdsClient.sonar.projectBaseDir=packages/common/pdsClient
common-pdsClient.sonar.sources=.
common-pdsClient.sonar.javascript.lcov.reportPaths=coverage/lcov.info

common-lambdaUtils.sonar.projectBaseDir=packages/common/lambdaUtils
common-lambdaUtils.sonar.sources=.
common-lambdaUtils.sonar.javascript.lcov.reportPaths=coverage/lcov.info

common-authFunctions.sonar.projectBaseDir=packages/common/authFunctions
common-authFunctions.sonar.sources=.
common-authFunctions.sonar.javascript.lcov.reportPaths=coverage/lcov.info


common-doHSClient.sonar.projectBaseDir=packages/common/doHSClient
common-doHSClient.sonar.sources=.
common-doHSClient.sonar.javascript.lcov.reportPaths=coverage/lcov.info

common-dynamoFunctions.sonar.projectBaseDir=packages/common/dynamoFunctions
common-dynamoFunctions.sonar.sources=.
common-dynamoFunctions.sonar.javascript.lcov.reportPaths=coverage/lcov.info

testingSupport.sonar.projectBaseDir=packages/testingSupport
testingSupport.sonar.sources=.
testingSupport.sonar.javascript.lcov.reportPaths=coverage/lcov.info
