name: merge to main workflow

on:
  push:
    branches: [ main ]

permissions: {}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@ba4bcd7fa2367cc44c9078adb96a654236d3691a
    with:
      verify_published_from_main_image: true
    permissions:
      attestations: read
      contents: read
      packages: read
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@ba4bcd7fa2367cc44c9078adb96a654236d3691a
    needs: [ get_config_values ]
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    needs: [quality_checks, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      dry_run: true
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}

  package_code:
    needs: [ tag_release, get_config_values ]
    uses: ./.github/workflows/cdk_package_code.yml
    permissions:
      contents: read
      packages: read
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}

  release_dev:
    needs: [ tag_release, package_code, get_config_values ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      contents: write
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      SERVICE_NAME: cpt-ui
      TARGET_ENVIRONMENT: dev
      VERSION_NUMBER: ${{needs.tag_release.outputs.version_tag}}
      COMMIT_ID: ${{github.sha}}
      useMockOidc: true
      JWT_KID: "eps-cpt-ui-dev"
      LOG_LEVEL: "DEBUG"
      REACT_LOG_LEVEL: "debug"
      LOG_RETENTION_IN_DAYS: 30
      IS_PULL_REQUEST: false
    secrets: inherit

  release_qa:
    needs: [ tag_release, release_dev, package_code, get_config_values ]
    uses: ./.github/workflows/release_all_stacks.yml
    permissions:
      contents: write
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      SERVICE_NAME: cpt-ui
      TARGET_ENVIRONMENT: qa
      VERSION_NUMBER: ${{needs.tag_release.outputs.version_tag}}
      COMMIT_ID: ${{github.sha}}
      useMockOidc: true
      JWT_KID: "eps-cpt-ui-qa"
      LOG_LEVEL: "DEBUG"
      REACT_LOG_LEVEL: "debug"
      LOG_RETENTION_IN_DAYS: 30
      IS_PULL_REQUEST: false
    secrets: inherit
