name: "Delete old cloudformation stacks"

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"

permissions: {}
jobs:
  delete-old-cloudformation-stacks:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout local github scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          sparse-checkout: |
            .github/scripts
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: cpt-ui-delete-old-cloudformation-stacks

      - name: delete stacks
        shell: bash
        working-directory: .github/scripts
        run: ./delete_stacks.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
