name: release all stacks

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      useMockOidc:
        type: boolean
        default: false
      RUN_REGRESSION_TESTS:
        type: boolean
        default: true
      LOG_LEVEL:
        type: string
      JWT_KID:
        type: string
      REACT_LOG_LEVEL:
        type: string
        required: true
      LOG_RETENTION_IN_DAYS:
        type: string
        required: true
      IS_PULL_REQUEST:
        type: boolean
        required: true
      pinned_image:
        required: true
        type: string
permissions: {}
jobs:
  release_all_code:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
    env:
      AWS_MAX_ATTEMPTS: 20
    steps:
      - &copy_tool_versions
        name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"

      - &download_build_artifact
        name: build_artifact download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: build_artifact

      - &extract_build_artifact
        name: extract build_artifact
        run: tar -xf artifact.tar

      - &configure_aws_credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: prescription-tracker-ui-deployment

      - name: check if fresh stateful stack deployment
        id: check_fresh_stateful_stack
        run: |
          CF_LONDON_EXPORTS=$(aws cloudformation list-exports --region eu-west-2 --output json)
          RUM_APP_ID=$(echo "$CF_LONDON_EXPORTS" | \
              jq \
              --arg EXPORT_NAME "${SERVICE_NAME}:rum:rumApp:Id" \
              -r '.Exports[] | select(.Name == $EXPORT_NAME) | .Value')

          FRESH_STATEFUL_STACK="false"
          if [ -z "${RUM_APP_ID}" ]; then
            echo "RUM_APP_ID not found - fresh stateful stack deployment"
            FRESH_STATEFUL_STACK="true"
          fi

          echo "FRESH_STATEFUL_STACK=$FRESH_STATEFUL_STACK" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}

      - name: Initial Deploy of Stateful Stacks
        if: ${{ steps.check_fresh_stateful_stack.outputs.FRESH_STATEFUL_STACK == 'true'
          }}
        run: |
          CDK_STACK_NAME="StatefulStack UsCertsStack" \
          CDK_CONFIG_rumCloudwatchLogEnabled=false \
          npm run cdk-deploy --workspace packages/cdk -- \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:JwtPrivateKey=${CDK_CONFIG_jwtPrivateKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeApiKey=${CDK_CONFIG_apigeeApiKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeSecretKey=${CDK_CONFIG_apigeeSecretKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeDoHSApiKey=${CDK_CONFIG_apigeeDoHSApiKey}"
        shell: bash
        env: &deployment_env_vars
          CDK_CONFIG_serviceName: "${{ inputs.SERVICE_NAME }}"
          CDK_CONFIG_versionNumber: "${{ inputs.VERSION_NUMBER }}"
          CDK_CONFIG_commitId: "${{ inputs.COMMIT_ID }}"
          CDK_CONFIG_isPullRequest: "${{ inputs.IS_PULL_REQUEST }}"
          CDK_CONFIG_environment: "${{ inputs.TARGET_ENVIRONMENT }}"
          CDK_CONFIG_rumCloudwatchLogEnabled: "true"
          CDK_CONFIG_useMockOidc: "${{ inputs.useMockOidc }}"
          CDK_CONFIG_primaryOidcClientId: "${{ secrets.CIS2_OIDC_CLIENT_ID }}"
          CDK_CONFIG_mockOidcClientId: "${{ secrets.MOCK_OIDC_CLIENT_ID }}"
          CDK_CONFIG_apigeeApiKey: "${{ secrets.APIGEE_API_KEY }}"
          CDK_CONFIG_apigeeSecretKey: "${{ secrets.APIGEE_API_SECRET }}"
          CDK_CONFIG_apigeeDoHSApiKey: "${{ secrets.APIGEE_DOHS_API_KEY }}"
          CDK_CONFIG_logRetentionInDays: "${{ inputs.LOG_RETENTION_IN_DAYS }}"
          CDK_CONFIG_logLevel: "${{ inputs.LOG_LEVEL }}"
          CDK_CONFIG_reactLogLevel: "${{ inputs.REACT_LOG_LEVEL }}"
          CDK_CONFIG_jwtPrivateKey: "${{ secrets.JWT_PRIVATE_KEY }}"
          CDK_CONFIG_jwtKid: "${{ inputs.JWT_KID }}"
          CDK_CONFIG_cloudfrontOriginCustomHeader: "${{ secrets.CLOUDFRONT_ORIGIN_CUSTOM_HEADER }}"
          REQUIRE_APPROVAL: "never"

      - name: Deploy Stateful Stacks
        run: |
          CDK_STACK_NAME="StatefulStack UsCertsStack" \
          npm run cdk-deploy --workspace packages/cdk -- \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:JwtPrivateKey=${CDK_CONFIG_jwtPrivateKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeApiKey=${CDK_CONFIG_apigeeApiKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeSecretKey=${CDK_CONFIG_apigeeSecretKey}" \
            --parameters "${CDK_CONFIG_serviceName}-stateful-resources:ApigeeDoHSApiKey=${CDK_CONFIG_apigeeDoHSApiKey}"
        shell: bash
        env: *deployment_env_vars

      - name: Deploy Stateless Stack
        run: CDK_STACK_NAME="StatelessStack UsStatelessStack" npm run cdk-deploy
          --workspace packages/cdk
        shell: bash
        env: *deployment_env_vars

  update_front_door:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    needs: [ release_all_code ]
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
    env:
      AWS_MAX_ATTEMPTS: 20
    steps:
      - *copy_tool_versions
      - *download_build_artifact
      - *extract_build_artifact
      - *configure_aws_credentials
      - name: Deploy Front Door Stack
        run: CDK_STACK_NAME=FrontDoorStack npm run cdk-deploy --workspace packages/cdk
        shell: bash
        env: *deployment_env_vars

  update_github_pages:
    runs-on: ubuntu-22.04
    if: ${{ inputs.IS_PULL_REQUEST == false }}
    needs: [ update_front_door ]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: true

      - name: update release tag in github pages
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "_data/${TARGET_ENVIRONMENT}_latest.csv"
          git add "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git commit -m "update releases for ${TARGET_ENVIRONMENT}"
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"
        env:
          TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}

  regression_tests:
    name: Regression Tests
    uses: ./.github/workflows/run_regression_tests.yml
    if: ${{ inputs.RUN_REGRESSION_TESTS == true }}
    needs: [ update_front_door ]
    permissions:
      contents: write
      id-token: write

    with:
      ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
      VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      pinned_image: ${{ inputs.pinned_image }}
    secrets:
      REGRESSION_TESTS_PEM: ${{ secrets.REGRESSION_TESTS_PEM }}
